In [ ]:
import shutil
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import ranksums
import os
import sys

import plotly.graph_objects as go 
import shutil
import plotly.express as px
import numpy as np 



dir_saveresults='/Users/chiaranotturnogranieri/Downloads/notturno/deseq2/menopause_status/BRCA'
tumor='BRCA'

path_result=os.path.join(dir_saveresults,'result_'+tumor+'.txt')
print(path_result)
df=pd.read_csv(path_result,sep="\t")
display(df)

df['padj']=np.log10(df['padj'])*(-1)
display(df)
#plt
#plotly_volcano(df,dir_saveresults,tumor)

In [ ]:
def plotly_volcano(df):
    fig=go.Figure()
    trace1=go.Scatter(
        x=df['log2FoldChange'],
        y=df['padj'],
        mode='markers',
        hovertext=list(df.index),
       

    )
    fig.add_trace(trace1)
    fig.add_hline(y=-np.log10(0.05),line_dash="dash")
    fig.add_vline(x=1,line_dash="dash")
    fig.add_vline(x=-1,line_dash="dash")
    fig.show()
   # fig.write_html(cartella+'/'+tumor+'.html')



def plotly_volcano(df):
    # Criteri per la colorazione
    #display(df)
    significance_threshold = -np.log10(0.05)
    fold_change_threshold = 1
    
    # Trasformazione del padj con -log10
    

    # Creiamo una colonna 'color' basata sui criteri di significatività
    df['color'] = 'grey'  # default colore

    df.loc[(df['padj'] > significance_threshold), 'color'] = 'blue'  
    df.loc[df['log2FoldChange'] > fold_change_threshold, 'color'] = 'red'  # Up-regolati
    df.loc[df['log2FoldChange'] < -fold_change_threshold, 'color'] = 'red'  # Up-regolati
   
   
    # Creazione del grafico
    fig = go.Figure()

    trace1 = go.Scatter(
        x=df['log2FoldChange'],
        y=df['padj'],
        mode='markers',
        marker=dict(
            color=df['color'],  # Usa la colonna color per colorare i punti
            size=10
        ),
        hovertext=list(df.index),  # Nome dei geni
    )
    
    fig.add_trace(trace1)
    
    # Linee di cutoff per la significatività
    fig.add_hline(y=(significance_threshold), line_dash="dash", line_color="black")  # Padj cutoff
    fig.add_vline(x=fold_change_threshold, line_dash="dash", line_color="black")  # Fold change positivo cutoff
    fig.add_vline(x=-fold_change_threshold, line_dash="dash", line_color="black")  # Fold change negativo cutoff

    # Aggiungere titoli e assi
    fig.update_layout(
        title="Volcano Plot",
        xaxis_title="log2 Fold Change",
        yaxis_title="-log10(padj)"
    )
    
    fig.show()



plotly_volcano(df)

In [2]:
import pandas as pd
import os 
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import subprocess
from pathlib import Path
import configparser
from scipy.stats import ranksums
import numpy as np
from lifelines import KaplanMeierFitter
from lifelines.statistics import logrank_test
from lifelines.plotting import add_at_risk_counts
from statsmodels.stats import multitest as multi
import plotly.express as px
import plotly.graph_objects as go 
import shutil

#######################################################################################
#                              Carica il file di configurazione                       #
#######################################################################################

config = configparser.ConfigParser()
#script_dir = Path(__file__).parent

# Costruisci il percorso relativo al file di configurazione
config_file ='/Users/chiaranotturnogranieri/Desktop/progetti/git/web_app/webserver/webserver/conf.ini'

config.read(config_file) 
#directory base
output_data = config['Paths']['output_data']
base_dir = config.get('Paths', 'base_dir', fallback='')

# Costruisci i percorsi completi
def get_full_path(relative_path):
    return os.path.join(base_dir, relative_path)

# Accesso ai valori e costruzione dei percorsi
if 'miRNA' in config:
    miRNA_name = get_full_path(config['miRNA']['name'])
    miRNA_dataframe = get_full_path(config['miRNA']['dataframe'])

if 'gene' in config:
    gene_name_ENSG = get_full_path(config['gene']['name_ENSG'])
    gene_dataframe = get_full_path(config['gene']['dataframe'])
    gene_dataframe_FPKM = get_full_path(config['gene']['dataframe_FPKM'])

if 'protein' in config:
    protein_name = get_full_path(config['protein']['name'])
    protein_dataframe = get_full_path(config['protein']['dataframe'])

if 'clinical' in config:
    clinical_data= get_full_path(config['clinical']['dati_clinici'])
    dati_age= get_full_path(config['clinical']['dati_age'])
    clinical_OS= get_full_path(config['clinical']['clinical_OS'])

if 'os' in config:
    os_pathway=get_full_path(config['os']['os_pathway'])

if 'TCGA' in config:
    TCGA_path=get_full_path(config['tcga']['split_count'])

In [7]:

def what_is_my_object_gene(gene,control):
    if control=='protein':
        if gene in open(protein_name).read().split("\n"):
            return(gene,'protein','peptide_target',protein_dataframe)
        else:
            return(0) #nome errato
   
    else:
         #implementato per prendere in input anche l'ENSG inserito senza versione.
        df_ensg= pd.read_csv(gene_name_ENSG,sep='\t')
        
        result_index = df_ensg[(df_ensg['gene_id_version'] == gene) | (df_ensg['gene_id'] == gene) | (df_ensg['gene_symbol'] == gene)].index
        if not result_index.empty:
            gene_version=df_ensg.loc[result_index[0],'gene_id_version']

            return (gene_version,'gene','gene_id',int(result_index[0]))
    
        if gene in open(miRNA_name).read().split("\n"):
            return (gene,'miRNA','miRNA_ID',miRNA_dataframe)

        else:
            return(0) #nome errato
    
def open_df_gene(input,tumor,feature,cartella):
    if feature == 'patient_status':
        #print(input)
        posizione="-e "+str(input[3]+2)+"p"
        #creiamo un dataframe piu piccolo dove c'è solo la riga del gene che è stato selezionato
        path=cartella+'/'+str(input[0])+"_df.txt"
        out_file=open(path,"w")
        subprocess.call(["sed","-n", "-e 1p", posizione, gene_dataframe],stdout=out_file)
        return(path)
                
    else:
        path_df="Dataframe_FPKM_"+tumor+".csv"
        path=os.path.join(gene_dataframe_FPKM,path_df)
        return(path)

def open_dataframe(gene,tumor,feature,cartella,control):
    input=what_is_my_object_gene(gene,control)
    if input!=0:
        if input[1]=='gene':
            #print(feature)
            path=open_df_gene(input,tumor,feature,cartella) #bisogna vedere in base al tipo di feature che viene passata
            df=pd.read_csv(path)
            df=df.set_index(input[2])
            return(df, input[1],input[0])
        else:
            df=df=pd.read_csv(input[3])
            df=df.set_index(input[2])
            return(df,input[1],input[0])
    else: 
        #print("search for the entered name is not available")
        return(0)
    

def plotly_plot(feature,d, gene,cartella,ogg):
        print(list(set(d[feature])))
        fig = px.scatter(x=range(10), y=range(10))
        fig=px.box(d,y=gene,x=feature,color=feature) #points = 'all'
        if ogg[1]== "miRNA":
                fig.update_layout(yaxis_type="log")
        #fig.write_html(cartella+'/'+gene+'_'+feature+'.html')
        fig.show()


def ranksum_test(gene,d,feature,cartella):
    #ranksum test per p-value
    p=list(set(d[feature]))
    
    df1_mask=d[feature]== p[0]
    dp0=d[df1_mask]
    
    df1_mask=d[feature]== p[1]
    dp1=d[df1_mask]

    w, p_value = ranksums(list(dp0[gene]), list(dp1[gene]))
    if p_value=='':
        p_value='not significant'
    # Dimensione dei campioni
    size_dp0 = len(dp0)
    size_dp1 = len(dp1)
    
    # Creazione del dizionario dei risultati
    results = {
        "Gene": gene,
        "Feature": feature,
        "Group 1":p[0],
        "Group 2":p[1],
        "Sample Size Group 1": size_dp0,
        "Sample Size Group 2": size_dp1,
        "P-value": p_value
    }
    
    # Creazione di un DataFrame per facilitare l'output
    results_df = pd.DataFrame([results])
    
    # Scrittura su file CSV
    output_file=os.path.join(cartella,'Result.txt')
    display(results_df)
    #results_df.to_csv(output_file, index=False)
    
    return(p_value)





def df_feature(ogg, tumor, feature):
    x=pd.read_csv(clinical_data)
    df1_mask=x['acronym']== tumor
    dfclinical=x[df1_mask]

    if feature=="age_at_initial_pathologic_diagnosis":
       # dfclinical = dfclinical.dropna(subset=['age_at_initial_pathologic_diagnosis'])
        dfclinical[feature] = pd.to_numeric(dfclinical[feature], errors='coerce').astype('Int64')


        median=dfclinical[feature].median()
        
        lista_age=[]
        for ele in dfclinical[feature]:
            
            ele=int(ele)
            if ele<=median:
                lista_age.append("under")
            else:
                lista_age.append("over")
                
        dfclinical=dfclinical.rename(columns={feature:"age"})
        dfclinical[feature]=lista_age

    return (dfclinical)
    

def crealista(dffeat,df,feature):
    #lista di samples di cui abbiamo le features e dati di espressione
    
    #caso specifico se abbiamo feature:patient_status
    if feature=='patient_status':
        lista=list(dffeat['bcr_patient_barcode'])
        listaf01=[]
        listaf=[]
        for ele in df.columns:
            if ele[:-4] in lista and ele[-1]!="x" and ele[-1]!='y':
                listaf01.append(ele)

        
        return listaf01

    #altrimenti con tutte le altre feature:
    else:
        lista=list(dffeat['bcr_patient_barcode'])
        
        listaf01=[]
        listaf=[]
        
        for ele in df.columns:
            if ele[:-4] in lista and ele[-1]!="x" and ele[-1]!='y':
                if int(ele[-3:-1])<11:
                    if ele[:-4] not in listaf:
                        listaf.append(ele[:-4])
                        listaf01.append(ele)

        if len(listaf)==len(listaf01):
            return listaf, listaf01
        else:
            return 0

import pandas as pd
import os 
import sys
import subprocess


if __name__ == "__main__":
    #parametri in input:
    gene='ENSG00000242268.2'
    tumor= 'BRCA'
    feature= 'menopause_status'
    # gene='hsa-let-7a-1'
    # tumor= 'ACC'
    # feature= 'gender'
    cartella='/Users/chiaranotturnogranieri/Desktop/progetti/git/web_app/webserver/rolls/static/media/saveanalisi/prova'
    control=''
    ogg=open_dataframe(gene,tumor,feature,cartella,control)
   
    if ogg!=0:
        gene=ogg[2]
        df=ogg[0]
        dffeat=df_feature(ogg[1], tumor, feature) #df features
        #display(dffeat)
        dffeat = dffeat.dropna(subset=[feature])
        #display(dffeat)
        if feature== 'patient_status':
            listaf0= crealista(dffeat, df,feature)
            
            lista_exp=[]#lista valori espressione
            lista_feature=[]
            for ele in df[listaf0]:
                lista_exp.append(df.loc[gene,ele])
                if int(ele[-3:-1])<11:
                    lista_feature.append('Tumor')
                else:
                    lista_feature.append('Ctrl')

            #controllo di avere sia dati tumorali che di controllo
            t=0
            c=0
            for ele in lista_feature:
                if ele== 'Tumor':
                    t+=1
                else:
                    c+=1
            if t==0 or c==0:
                print('there is not enough data')               
            
            
            
            d=pd.DataFrame({'nome01':listaf0, gene: lista_exp, feature: lista_feature})
        
        
        else:
            listaf, listaf01= crealista(dffeat, df,feature)
            dffeat=dffeat[['bcr_patient_barcode',feature]]

            #creo un dframe finale
            dframe=pd.DataFrame({'nome01':listaf01, 'bcr_patient_barcode':listaf})
            d= dframe.merge(dffeat)

            lista_exp=[] #lista valori espressione
            for ele in d['nome01']:
                lista_exp.append(df.loc[gene,ele])

            d[gene]=lista_exp

        #plt
        plotly_plot(feature,d, gene,cartella,ogg)

        #p-value
        print(ranksum_test(gene,d,feature,cartella))
    else:
        print(0)

,bcr_patient_barcode,acronym,gender,age_at_initial_pathologic_diagnosis,radiation_therapy,pathologic_stage,tobacco_smoking_history,menopause_status,alcohol_history_documented,diabetes
504,TCGA-3C-AAAU,BRCA,FEMALE,55,NO,NaN,NaN,pre_menopause,NaN,NaN
505,TCGA-3C-AALI,BRCA,FEMALE,50,YES,stageI_II,NaN,post_menopause,NaN,NaN
506,TCGA-3C-AALJ,BRCA,FEMALE,62,NO,stageI_II,NaN,post_menopause,NaN,NaN
507,TCGA-3C-AALK,BRCA,FEMALE,52,NO,stageI_II,NaN,NaN,NaN,NaN
508,TCGA-4H-AAAK,BRCA,FEMALE,50,NO,stageIII_IV,NaN,post_menopause,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1598,TCGA-WT-AB44,BRCA,FEMALE,77,YES,stageI_II,NaN,post_menopause,NaN,NaN
1599,TCGA-XX-A899,BRCA,FEMALE,46,YES,stageIII_IV,NaN,post_menopause,NaN,NaN
1600,TCGA-XX-A89A,BRCA,FEMALE,68,YES,stageI_II,NaN,post_menopause,NaN,NaN
1601,TCGA-Z7-A8R5,BRCA,FEMALE,61,NO,stageIII_IV,NaN,post_menopause,NaN,NaN
1602,TCGA-Z7-A8R6,BRCA,FEMALE,46,NO,stageI_II,NaN,pre_menopause,NaN,NaN

,bcr_patient_barcode,acronym,gender,age_at_initial_pathologic_diagnosis,radiation_therapy,pathologic_stage,tobacco_smoking_history,menopause_status,alcohol_history_documented,diabetes
504,TCGA-3C-AAAU,BRCA,FEMALE,55,NO,NaN,NaN,pre_menopause,NaN,NaN
505,TCGA-3C-AALI,BRCA,FEMALE,50,YES,stageI_II,NaN,post_menopause,NaN,NaN
506,TCGA-3C-AALJ,BRCA,FEMALE,62,NO,stageI_II,NaN,post_menopause,NaN,NaN
508,TCGA-4H-AAAK,BRCA,FEMALE,50,NO,stageIII_IV,NaN,post_menopause,NaN,NaN
509,TCGA-5L-AAT0,BRCA,FEMALE,42,YES,stageI_II,NaN,post_menopause,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1598,TCGA-WT-AB44,BRCA,FEMALE,77,YES,stageI_II,NaN,post_menopause,NaN,NaN
1599,TCGA-XX-A899,BRCA,FEMALE,46,YES,stageIII_IV,NaN,post_menopause,NaN,NaN
1600,TCGA-XX-A89A,BRCA,FEMALE,68,YES,stageI_II,NaN,post_menopause,NaN,NaN
1601,TCGA-Z7-A8R5,BRCA,FEMALE,61,NO,stageIII_IV,NaN,post_menopause,NaN,NaN
1602,TCGA-Z7-A8R6,BRCA,FEMALE,46,NO,stageI_II,NaN,pre_menopause,NaN,NaN

['pre_menopause', 'post_menopause']

/Users/chiaranotturnogranieri/anaconda3/lib/python3.11/site-packages/plotly/express/_core.py:1979: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

,Gene,Feature,Group 1,Group 2,Sample Size Group 1,Sample Size Group 2,P-value
0,ENSG00000242268.2,menopause_status,pre_menopause,post_menopause,227,741,0.273647

0.27364664855809095

In [ ]:
def read_clinical_data():
    x=pd.read_csv(clinical_data)
    x=x.set_index("bcr_patient_barcode")
    return(x)

def what_is_my_object_gene(gene):
    #implementato per prendere in input anche l'ENSG inserito senza versione.
    if 'ENSG' in gene:
        df_ensg= pd.read_csv(gene_name_ENSG,sep='\t')
    
        result_index = df_ensg[(df_ensg['gene_id_version'] == gene) | (df_ensg['gene_id'] == gene)].index
        if not result_index.empty:
            gene_version=df_ensg.loc[result_index[0],'gene_id_version']

            return (gene_version,'gene','gene_id',int(result_index[0]))
        else:
            return(0)

    if gene in open(protein_name).read().split("\n"):
        return(gene,'protein','peptide_target',protein_dataframe)

    if gene in open(miRNA_name).read().split("\n"):
        return (gene,'miRNA','miRNA_ID',miRNA_dataframe)

    else:
        return(0)

def detect_if_gene_mirna_proteina(gene, cartella):
    
    if gene in open(miRNA_name).read().split("\n"):
        os.mkdir(cartella)
        return(['miRNA',"miRNA_ID",miRNA_dataframe])
    
    if gene in open(gene_name_ENSG).read().split("\n"):
        os.mkdir(cartella)
        listageni=open(gene_name_ENSG).read().strip().split("\n")
        posizione="-e "+str(listageni.index(gene)+1)+"p"
        
        #creiamo un dataframe piu piccolo dove c'è solo la riga del gene che è stato selezionato
        path=cartella+'/'+gene+"_df.txt"
        out_file=open(path,"w")
        subprocess.call(["sed","-n", "-e 1p", posizione, gene_dataframe ],stdout=out_file)
        
        return(['gene','gene_id',path])

    if gene in open(protein_name).read().split("\n"):
        os.mkdir(cartella)
        return(['protein', "peptide_target",protein_dataframe])
    
    else:
        return(0) #la ricerca non è disponibile per il nome inserito

def open_dataframe_gene_boxplot_all_tumor(gene,listanomi01, path_dataframe, index):
    if gene == 'miRNA':
        df=pd.read_csv(path_dataframe,usecols=listanomi01)
        df=df.set_index(index)
        return(df)
    if gene == 'gene':
        df=pd.read_csv(path_dataframe,usecols=listanomi01)
        df=df.set_index(index)
        return (df)
    if gene =='protein':
        df=pd.read_csv(path_dataframe,usecols=listanomi01)
        df=df.set_index(index)
        return (df)
    else: 
        print("per il nome inserito non è disponibile la ricerca")
        return 0



def box_plot_all_tumor(df1, cartella, gene, feature):
    
    sns.set_theme(rc={'figure.figsize':(25.7,8.27)})
    sns.set_style("white")

    my_order = df1.groupby(by=["tumor"])[gene].median().iloc[::-1].sort_values().index
    ax=sns.boxplot(x="tumor", y=gene, hue=feature, data=df1, palette="Set2", width=0.7, order=my_order)
    ax.set_yscale("log")
    
    plt.savefig(cartella+'/'+gene+'_'+feature+'.jpg')


def df_feature_age(x,feature):
    if feature=="age_at_initial_pathologic_diagnosis":
        #path_age=os.path.join()
        df=pd.read_csv(dati_age)
        display(df)
        df=df.set_index('acronym')
        
        lista_age=[]
        x1=x
        x1 = x1.drop(x1[x1[feature]== '[Not Available]'].index)

        for tumor,age in zip(x1['acronym'],x1[feature]):
            age=int(age)
            mediana=df.loc[tumor,'median_age']
            
            if age<=mediana:
                lista_age.append("under")
            else:
                lista_age.append("over")

        x1=x1.rename(columns={"age_at_initial_pathologic_diagnosis":"age"})
        x1[feature]=lista_age

        return(x1) 


#per la feature patient status
def crealista_patient_status(dffeat,listamiRNA,ogg):
    lista=list(dffeat.index)
        
    listaf01=[ogg[1]]
    listaf=[]
    for ele in listamiRNA:
        if ele[:-4] in lista and ele[-1]!="x" and ele[-1]!='y':
            listaf01.append(ele)
            listaf.append(ele[:-4])
            
    return listaf01,listaf


def pulisci_df(df,feature):
    for tumor in set(list(df.tumor)):
        df1=df
        df1_mask=df['tumor'] == tumor
        df1=df1[df1_mask]

        lista_feature=((list(df1[feature])))
        t=0
        c=0
        for ele in lista_feature:
            if ele== 'Tumor':
                t+=1
            else:
                c+=1       

        #print(tumor, t, c)
        if t==0 or c==0:
            df.drop(df.index[df['tumor'] == tumor], inplace = True)
            
    return df


#ranksum test per p-value
def p_value(df, cartella,feature,gene):
    f=open(cartella+'/result.txt','w')
    f.write('tumor'+'\t'+'p-value'+'\n')
    tumori=set(list(df.tumor))
    for tumor in tumori:
        p=list(set(df[feature]))

        df1=df
        df1_mask=df1['tumor'] == tumor
        df1=df1[df1_mask]


        filtered_df = df1[df1[feature].eq(p[0])]
        list0= list(filtered_df[gene])


        filtered_df = df1[df1[feature].eq(p[1])]
        list1= list(filtered_df[gene])

        w, p = ranksums(list0, list1)
        print(tumor, p)
        f.write(tumor+"\t"+str(p)+"\n")


#################################    
#             MAIN              #
#################################   

if __name__ == "__main__":
    #parametri in input:
    gene= 'ENSG00000242268.2'
    feature= 'age_at_initial_pathologic_diagnosis'
    cartella='/Users/chiaranotturnogranieri/Desktop/progetti/git/web_app/webserver/rolls/static/media/saveanalisi/prova'


    x=read_clinical_data()
   
    if feature=="age_at_initial_pathologic_diagnosis":
        x1=df_feature_age(x,feature)
    else:
        x1=x


    display(x1)

    # #aprire df
    # ogg_analisi=detect_if_gene_mirna_proteina(gene, cartella) #es. miRNA, miRNA_ID, 'pathdataframe.csv'
    # print(ogg_analisi)
    # if ogg_analisi!=0:
        
    #     #lista samples df expression gene/miRNA/prot
    #     dd=pd.read_csv(ogg_analisi[2],nrows=1)
    #     listamiRNA=list(dd.columns[1:])


    #     #patient status
    #     if feature== 'patient_status':    
    #         listanomi01, listanomi= crealista_patient_status(x, listamiRNA,ogg_analisi)
            
    #         #aprire df espressione
    #         d=open_dataframe_gene_boxplot_all_tumor(ogg_analisi[0],listanomi01, ogg_analisi[2],ogg_analisi[1])
            

    #         lista_exp=[]#lista valori espressione
    #         lista_feature=[]#lista valori feature
    #         for ele in d.columns:
    #             lista_exp.append(d.loc[gene,ele])
    #             if int(ele[-3:-1])<11:
    #                 lista_feature.append('Tumor')
    #             else:
    #                 lista_feature.append('Ctrl')
                    

    #     else:
    #         #list samples with clinical data
    #         listap=list(x1.index) 
            
    #         listanomi=[] #nomi con cui ricavare i dati clinici
    #         listanomi01=[ogg_analisi[1]] #nomi con cui ricavare dati di espressione
    #         for el in listamiRNA:
    #             if el[:-4] in listap and el[:-4] not in listanomi:
    #                 if int(el[-3:-1])<11:
    #                     listanomi.append(el[:-4])
    #                     listanomi01.append(el)


    #         #df espressione solo dei campioni di cui abbiamo i dati clinici
    #         print(ogg_analisi[2])
    #         d=open_dataframe_gene_boxplot_all_tumor(ogg_analisi[0],listanomi01, ogg_analisi[2])
    #         print('here')


    #     colonna1=list(d.loc[gene,])
    #     colonna2=list(x1.loc[listanomi, "acronym"])
    #     if feature== 'patient_status':
    #         colonna3=lista_feature
    #     else:
    #         colonna3=list(x1.loc[listanomi, feature])


    #     df=pd.DataFrame({gene:colonna1, 'tumor':colonna2, feature:colonna3})
    #     df=df.dropna()


    #     #rimuovere i tumori che non hanno il ctrl 
    #     if feature=='patient_status':
    #         df=pulisci_df(df,feature)  

    #     box_plot_all_tumor(df, cartella, gene, feature)
    #     p_value(df, cartella,feature,gene)

    # else:
    #     print('Ricerca non disponibile per il nome inserito')